config/routes.rb
Rails.application.routes.draw do
  get '/calendar/:year/:month', to: 'events#show', as: 'show_event'
  get '/event/new', to: 'events#new', as: 'new_event'
  post '/event', to: 'events#create', as: 'create_event'
  get '/event/:id/edit', to: 'events#edit', as: 'edit_event'
  patch '/event/:id', to: 'events#update', as: 'update_event'
  put '/event/:id', to: 'events#update'

  delete '/event/:id', to: 'events#delete', as: 'delete_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
# This controlls application actions
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  MONTHS_ENG = {
    '1' => 'JANUARY', '2' => 'FEBRUARY', '3' => 'MARCH', '4' => 'APRIL', '5' => 'MAY', '6' => 'JUNE',
    '7' => 'JULY', '8' => 'AUGUST', '9' => 'SEPTEMBER', '10' => 'OCTOBER', '11' => 'NOVEMBER', '12' => 'DECEMBER'
  }.freeze
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper

  def show
    @year = params[:year]
    @month = params[:month]
    @months_eng = MONTHS_ENG

    uri = URI.parse('http://10.10.10.10:4567/events/' + @year + '/' + @month)
    request = Net::HTTP.get(uri)
    @response = JSON.parse(request)
  end

  def new
    @year = params[:year]
    @month = params[:month]
    @day = params[:day]
    @start_hour = params[:start_hour]
    @start_min = params[:start_min]
    @end_hour = params[:end_hour]
    @end_min = params[:end_min]
    @schedule = params[:schedule]
  end

  def create
    if form_error?
      then redirect_to new_event_path(year: params[:year], month: params[:month], day: params[:day],
                                      start_hour: params[:start_hour], start_min: params[:start_min],
                                      end_hour: params[:end_hour], end_min: params[:end_min],
                                      schedule: params[:schedule]),
                       flash: { notice: '不正な入力があります' }
    else
      Net::HTTP.new('10.10.10.10', '4567')
               .request(Net::HTTP::Post.new(return_create_uri))

      redirect_to show_event_path(params[:year], params[:month])
    end
  end

  def edit
    @id = params[:id]
    @array_date = params[:date].split('-')
    @array_start = params[:start].split('T')[1].split(':')
    @array_end = params[:end].split('T')[1].split(':')
    @schedule = params[:schedule]
  end

  def update
    if form_error?
      then redirect_to edit_event_path(id: params[:id],
                                       date: shape_date(params[:year], params[:month], params[:day], '-'),
                                       start: 'T' + shape_time(params[:start_hour], params[:start_min], ':'),
                                       end: 'T' + shape_time(params[:end_hour], params[:end_min], ':'),
                                       schedule: params[:schedule]),
                       flash: { notice: '不正な入力があります' }
    else
      Net::HTTP.new('10.10.10.10', '4567')
               .request(Net::HTTP::Put.new(return_update_uri))

      redirect_to show_event_path(params[:year], params[:month])
    end
  end

  def delete
    Net::HTTP.new('10.10.10.10', '4567')
             .request(Net::HTTP::Delete.new(URI.parse('http://10.10.10.10:4567/events/' + params[:id])))
    redirect_to show_event_path(params[:year], params[:month])
  end
end

app/helpers/application_helper.rb
# This helps application
module ApplicationHelper
  def shape_date(year, month, day, symbol)
    year + symbol + month + symbol + day
  end

  def shape_time(hour, min, symbol)
    hour + symbol + min
  end

  def join_string(*array)
    array.join
  end

  def form_error?
    !params[:year].match(/\d{4}/) || !params[:month].match(/\d{1,2}/) ||
      !params[:day].match(/\d{1,2}/) || !params[:start_hour].match(/\d{1,2}/) ||
      !params[:start_min].match(/\d{1,2}/) || !params[:end_hour].match(/\d{1,2}/) ||
      !params[:end_min].match(/\d{1,2}/) || params[:schedule] == ''
  end

  def return_create_uri
    URI.parse(join_string('http://10.10.10.10:4567/events/',
                          params[:year], '/', params[:month],
                          '?date=',
                          shape_date(params[:year],
                                     params[:month],
                                     params[:day], '-'),
                          '&start=',
                          shape_time(params[:start_hour],
                                     params[:start_min], ':'),
                          '&end=',
                          shape_time(params[:end_hour],
                                     params[:end_min], ':'),
                          '&schedule=',
                          params[:schedule]))
  end

  def return_update_uri
    URI.parse(join_string('http://10.10.10.10:4567/events/',
                          params[:id],
                          '?date=',
                          shape_date(params[:year],
                                     params[:month],
                                     params[:day], '-'),
                          '&start=',
                          shape_time(params[:start_hour],
                                     params[:start_min], ':'),
                          '&end=',
                          shape_time(params[:end_hour],
                                     params[:end_min], ':'),
                          '&schedule=',
                          params[:schedule]))
  end
end

app/helpers/events_helper.rb
# This helps model "event"
module EventsHelper
end

app/views/events/edit.html.erb
<body class = 'new_body'>
  <h2> イベント編集 </h2>

  <% if flash[:notice] %>
    <div class = 'flash_notice' >
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= form_tag({ :controller => 'events', :action => 'update' }, { method: 'put' }) do %>

  <label class = 'new_event_label' >
    イベント内容
  </label>
  <div class = 'new_event_schedule' >
    <%= text_area_tag :schedule, @schedule, class: 'text_area' %>
  </div>

  <label class = 'event_date_label' >
    日時
  </label>
  <p class = 'new_event_date' >
    <%= text_field_tag :year, @array_date[0], class: 'text_field_year' %>
    年
    <%= text_field_tag :month, @array_date[1], class: 'text_field' %>
    月
    <%= text_field_tag :day, @array_date[2], class: 'text_field' %>
    日
  </p>

  <p>
    <div class = 'new_event_time'>
      <label class = 'time_label'>
        開始 :
      </label>
      <%= text_field_tag :start_hour, @array_start[0], class: 'text_field' %>
      :
      <%= text_field_tag :start_min, @array_start[1], class: 'text_field' %>
    </div>

    <div class = 'new_event_time'>
      <label class = 'time_label'>
        終了 :
      </label>
      <%= text_field_tag :end_hour, @array_end[0], class: 'text_field' %>
      :
      <%= text_field_tag :end_min, @array_end[1], class: 'text_field' %>
    </div>
  </p>

  <div class = 'new_event_button'>
    <button class = 'button'>
      編集
    </button>
  </div>

  <% end %>

  <div class = 'delete_event_button'>
    <p>
      <%= button_to "削除", delete_event_path(@id, params: {year: @array_date[0], month: @array_date[1]}), method: :delete, data: {confirm: "本当に削除しますか?"}, class: 'delete_button' %>
    </p>
  </div>

<body>

app/views/events/new.html.erb
<body class = 'new_body'>
  <h2> 新規イベント </h2>

  <% if flash[:notice] %>
    <div class = 'flash_notice' >
      <%= flash[:notice] %>
    </div>
  <% end %>

  <%= form_tag({ :controller => 'events', :action => 'create' }, { method: 'post' }) do %>

  <label class = 'new_event_label' >
    イベント内容
  </label>
  <div class = 'new_event_schedule' >
    <%= text_area_tag :schedule, @schedule, class: 'text_area' %>
  </div>

  <label class = 'event_date_label' >
    日時
  </label>
  <p class = 'new_event_date' >
    <%= text_field_tag :year, @year, class: 'text_field_year' %>
    年
    <%= text_field_tag :month, @month, class: 'text_field' %>
    月
    <%= text_field_tag :day, @day, class: 'text_field' %>
    日
  </p>

  <p>
    <div class = 'new_event_time'>
      <label class = 'time_label'>
        開始 :
      </label>
      <%= text_field_tag :start_hour, @start_hour, class: 'text_field' %>
      :
      <%= text_field_tag :start_min, @start_min, class: 'text_field' %>
    </div>

    <div class = 'new_event_time'>
      <label class = 'time_label'>
        終了 :
      </label>
      <%= text_field_tag :end_hour, @end_hour, class: 'text_field' %>
      :
      <%= text_field_tag :end_min, @end_min, class: 'text_field' %>
    </div>
  </p>

  <div class = 'new_event_button'>
    <button class = 'button'>
      追加
    </button>
  </div>

  <% end %>

</body>

app/views/events/show.html.erb
<body class = 'show_body'>
  <h2>
    My Schedule
    <%= link_to '新規イベント', new_event_path, class: "new_event"%>
  </h2>
  <table>
    <caption>
      <div class = "date">
    　  <%= @months_eng[@month] + " " + @year %>
      </div>
    </caption>
    <tr class = "week_label">
      <th>Sunday</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
    </tr>
    <% first_day = Date.new(@year.to_i, @month.to_i, 1) %>
    <% sunday = first_day.beginning_of_week-1 %>
    <% (1..6).each do |i| %>
    <tr>
      <% (sunday..sunday + 6).each do |day| %>
        <% if (day == sunday) then %>
          <% if (day.strftime('%m').to_i == @month.to_i-1 && day.strftime('%d').to_i == day.end_of_month.strftime('%d').to_i-6) then break end %>
        <% end %>
        <% if (i == 6) then %>
          <% if (day == sunday) then %>
            <% if (day.strftime('%m').to_i == @month.to_i+1) then break end %>
          <% end %>
        <% end %>
        <td width="130" height="100" align="left" valign="top">
          <% if day.strftime('%m').to_i == @month.to_i then %>
          <div class = "day">
            <%= day.strftime('%d') %>
          </div>
          <% else %>
          <div class = "other_month">
            <%= day.strftime('%d').to_i %>
          </div>
          <% end %>
          <br>
          <% @response.each do |event| %>
            <% event_day = event["date"].split("-")[2] %>
            <% start_min = event["start"].split(":")[1] %>
            <% end_min = event["end"].split(":")[1] %>

          <% if day.strftime('%m') == @month && day.strftime('%d') == event_day then %>
          <div class = "events">
            <%= event["start"].to_time.hour.to_s + ":" + start_min + " ~ " + event["end"].to_time.hour.to_s + ":" + end_min %>
            <br>
            <%= link_to event["schedule"], edit_event_path(event["id"], event) %>
            <br>
          </div>
          <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
    <% sunday += 7%>
    <% end %>
  </table>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>